config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resource :header_color, only: %i[edit update]

  resources :questions do
    put 'hide', on: :member
  end

  resource :session, only: %i[new create destroy]

  resources :users, except: :index, param: :nickname

  resources :hashtags, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  REGEX = /#[[:word:]]+/
  
  has_many :hashtag_questions, dependent: :delete_all
  has_many :questions, through: :hashtag_questions

  validates :name, uniqueness: true
end

app/models/hashtag_question.rb
class HashtagQuestion < ApplicationRecord
  belongs_to :hashtag
  belongs_to :question

  validates :hashtag_id, uniqueness: { scope: :question_id }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :hashtag_questions, dependent: :delete_all
  has_many :hashtags, through: :hashtag_questions

  validates :body, presence: true, length: { maximum: 280 }

  after_commit :update_hashtags, on: %i[create update]


  private

  def update_hashtags
    self.hashtags =
      "#{body} #{answer}".downcase.scan(Hashtag::REGEX).uniq.map do |tag|
        Hashtag.find_or_create_by(name: tag.delete('#'))
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')

  has_secure_password

  has_many :questions, dependent: :delete_all

  before_validation :downcase_nickname, :downcase_email

  validates :nickname, presence: true, length: { maximum: 40 },
    uniqueness: true, format: { with: /\A\w+\z/ }

  validates :email, presence: true, uniqueness: true,
    format: { with: /\A[a-z\d+.\-]+@[a-z\d-]+(\.[a-z\d\-]+)*\.[a-z]+\z/ }

  def to_param
    nickname
  end

  private

  def downcase_nickname
    nickname&.downcase!
  end

  def downcase_email
    email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find(params[:id])
  end
end

app/controllers/header_colors_controller.rb
class HeaderColorsController < ApplicationController
  before_action :ensure_current_user

  def edit
  end

  def update
    color_params = params[:header_color][:color]
    header_color = "header_color_#{current_user.id}"
    session[header_color] = color_params

    redirect_to root_path, notice: 'Цвет панели изменен'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[edit update destroy hide]
  before_action :set_question_for_current_user, only: %i[edit update destroy hide]

  def new
    @user = User.find(params[:user_id])
    @question = Question.new(user: @user)
  end

  def create
    question_params = params.require(:question).permit(:body, :user_id)

    @question = Question.new(question_params)
    @question.author = current_user

    @user = User.find(question_params[:user_id])

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Новый вопрос создан!'
    else
      flash[:alert] = 'Не удалось создать вопрос!'

      render :new
    end
  end

  def edit
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Сохранили вопрос!'
    else
      flash.now[:alert] = 'Не удалось обновить вопрос!'

      render :edit
    end
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'Вопрос удалён!'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc).first(10)
    @users = User.order(created_at: :desc).first(10)
    @hashtags =
      Hashtag.joins(:questions).uniq
  end

  def hide
    @question.update(hidden: true)

    redirect_back_or_to(root_path)
  end

  private

  def check_captcha(model)
    if current_user.present?
      true
    else
      verify_recaptcha(model: model)
    end
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])
      &.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy show]
  before_action :authorize_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      redirect_to root_path, notice: 'Вы успешно зарегистрировались!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации'

      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = 'При попытке сохранить пользователя возникли ошибки'

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удалён'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  private

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11,14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end

  def navbar_color
    user_header_color = "header_color_#{current_user.id}" if current_user.present?

    if session[user_header_color].present?
      "style=background-color:#{session[user_header_color]}"
    end
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def display_hashtag(string)
    "##{string}"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user.nickname}"
  end
end

app/views/hashtags/show.html.erb
<div class="container">
  <h2 class="title-lg"><%= display_hashtag(@hashtag.name) %></h2>
</div>

<% @hashtag.questions.each do |question| %>
  <div class="mt-sm container">
    <p class="mb text-sm text-grey">
      Вопрос <%= link_to "##{question.id}", question_path(question) %>
      для юзера <%= link_to "#{display_nickname(question.user)}",
        user_path(question.user) %>
    </p>

    <%= render question %>

    <p class="mt text-sm">Хэштеги</p>
    <div class="mt-sm">
      <% question.hashtags.each do |hashtag| %>
        <%= link_to display_hashtag(hashtag.name), hashtag_path(hashtag),
          class: 'mr-sm text-sm hashtag' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/header_colors/edit.html.erb
<div class="container">
  <h2 class="title">Цвет панели</h2>
  <div class="mt">
    <%= form_with scope: :header_color, url: header_color_path,
      data: { turbo: false }, method: :put do |form| %>
      <p class="mt">
        <%= form.label :color, 'Выберите новый цвет для навигационной панели' %>
      </p>
      <p class="mt">
        <%= form.color_field :color, value: '#370617' %>
      </p>

      <p class="mt">
        <%= form.submit 'Сохранить', class: 'button button-main' %>
        <span class="text-sm">или <%= link_to 'вернуться', :back %></span>
      </p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar" <%= navbar_color %>>
        <p class="title-sm text-bold"><%= link_to 'Ask me!', root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to display_nickname(current_user), user_path(current_user),
              class: 'mr-sm' %>
            <%= button_to 'Выйти', session_path, method: :delete %>
          <% else %>
            <%= link_to 'Регистрация', new_user_path, class: 'button button-yellow mr-sm' %>
            <%= link_to 'Войти', new_session_path, class: 'button button-yellow' %>
          <% end %>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message-alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<% if question.errors.any? %>
  <div class="mt">
    <% question.errors.full_messages.each do |message| %>
      <p class="mb-sm text-red"><%= message %></p>
    <% end %>
  </div>
<% end %>

<div class="mt">
  <%= form_with model: question, data: { turbo: false } do |form| %>
    <%= form.hidden_field :user_id %>

    <p><%= form.label :body, 'Текст вопроса' %></p>
    <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

    <% if question.persisted? %>
      <p class="mt"><%= form.label :answer, 'Ответ' %></p>
      <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
    <% end %>

    <%= recaptcha_tags(noscript: false) unless current_user.present? %>

    <p class="mt">
      <%= form.submit 'Сохранить', class: 'button button-main' %>
      &nbsp;или&nbsp;
      <%= link_to 'вернуться', :back %>
    </p>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="<%= class_names(hidden: question.hidden?) %>">
  <% if question.author.present? %>
    <div class="mb-sm">
      <%= link_to display_nickname(question.author), user_path(question.author),
        class: 'text-bold mb nickname' %>
    </div>
  <% end %>

  <div class="mb-sm">
    <%= safe_join(question.body.split("\n"),tag(:br)) %>
  </div>

  <% if question.answer.present? %>
    <div class="mb-sm text-dark-red">
      <%= question.answer %>
    </div>
  <% end %>

  <div class="text-sm question-footer">
    <div class="text-grey">
      <%= l(question.created_at, format: :short) %>
    </div>

    <% if current_user == question.user %>
      <div>
        <% edit_icon = (question.answer.present? ? 'pencil' : 'reply') %>
        <%= link_to fa_icon(edit_icon), edit_question_path(question), title: 'Изменить вопрос',
          class: 'mr-sm' %>
        <%= button_to fa_icon('trash-o'), question_path(question), method: :delete,
          title: 'Удалить вопрос', class: 'mr-sm',
          form: { data: { turbo_confirm: 'Точно удалить вопрос?' }}%>
        <% unless question.hidden? %>
          <%= button_to fa_icon('eye-slash'), hide_question_path(question),
            method: :put, title: 'Скрыть вопрос',
            form: { data: { turbo_confirm: 'Скрыть вопрос?' }} %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактирование вопроса <%= @question.id %></h2>

  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">
    Недавно добавились
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: { user: user } %>
    <% end %>
  </div>
</div>

<div class="mt-sm container">
  <h2 class="title-lg">
    <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <p class="mb text-sm text-grey">
      Вопрос <%= link_to "##{question.id}", question_path(question) %>
      для юзера <%= link_to "#{display_nickname(question.user)}",
        user_path(question.user) %>
    </p>
    <%= render question %>
  </div>
<% end %>

<% unless @hashtags.empty? %>
  <div class="mt-sm container">
    <h2 class="title-lg mb">Список хэштегов</h2>
    <% @hashtags.each do |hashtag| %>
      <%= link_to display_hashtag(hashtag.name), hashtag_path(hashtag),
        class: 'mr-sm hashtag' %>
    <% end %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">Новый вопрос</h2>
  <p class="mb">для <%= link_to display_nickname(@user), user_path(@user) %></p>

  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title mb">Вопрос #<%= @question.id %></h2>
  <p class="mt-sm">
    <%= link_to "Все вопросы #{display_nickname(@question.user)}",
      user_path(@question.user) %>
  </p>
</div>

<div class="container mt-sm">
  <%= render 'question', question: @question %>

  <% unless @question.hashtags.empty? %>
    <p class="mt text-sm">Хэштеги</p>
    <div class="mt-sm">
      <% @question.hashtags.each do |hashtag| %>
        <%= link_to display_hashtag(hashtag.name), hashtag_path(hashtag),
          class: 'mr-sm text-sm hashtag' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/_empty_state.erb
<div class="mt-sm mb-sm container empty-state">
    <%= image_tag('group_26795.png') %>
    <p class="mt">У этого пользователя пока никто ничего не спросил</p>
    <p>Будьте первыми!</p>

    <%= link_to 'Спроси меня', new_question_path(user_id: user.id),
    class: 'button button-yellow mt' %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded mr ml mt">
  <a href="<%= user_path(user) %>">
    <%= image_tag user.gravatar_url, title: display_nickname(user),
      class: 'rounded' %>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Редактирование пользователя</h2>

  <div class="mt">
    <p>
      <%= image_tag @user.gravatar_url, title: display_nickname(@user),
        class: 'rounded' %>
    </p>
    <p class="mt text-sm">
      Чтобы добавить или поменять аватар - зарегистрируйтесь на
      <%= link_to 'Gravatar', 'https://gravatar.com' %> и загрузите фото
    </p>
  </div>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>
  
  <div class="mt">
    <%= form_with model: @user, data: { turbo: false } do |form| %>
      <p><%= form.label :name, 'Имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt-lg text-sm">
        Если не хотите менять пароль - оставьте эти поля пустыми!
      </p>

      <p class="mt"><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt">
        <%= form.label :password_confirmation, 'Подтверждение пароля' %>
      </p>
      <p><%= form.password_field :password_confirmation, 
        class: 'form-text-field' %></p>

      <p class="mt-lg">
        <%= form.submit "Сохранить", class: 'button button-main' %>
        <span class="text-sm">или <%= link_to 'вернуться', :back %></span>
      </p>
    <% end %>
  </div>

  <div class="mt-lg">
    <%= link_to 'Изменить цвет панели', edit_header_color_path, class: 'text-sm' %>
  </div>

  <div class="mt-lg">
    <%= button_to 'Удалить профиль', user_path(@user), method: :delete, 
      form: { data: { turbo_confirm: 'Вы точно хотите удалить свой профиль?' }}, 
      class: 'text-red text-sm' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Присоединяйся и спрашивай!</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: { turbo: false } do |form| %>
      <p><%= form.label :name, 'Ваше имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, 
        class: 'form-text-field' %></p>

      <p class="mt-lg">
        <%= form.submit "Зарегистрироваться", class: 'button button-main' %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box">
  <h2 class="title-lg mt-lg"><%= @user.name %></h2>

  <div class="mt">
    <%= render partial: 'users/user_avatar', locals: { user: @user } %>
  </div>

  <% if current_user == @user %>
    <p class="mt">
      <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
    </p>
  <% end %>

  <p class="text-bold mt mb-lg"><%= display_nickname(@user) %></p>
</div>

<% if @questions.empty? %>

  <%= render 'empty_state', user: @user %>

<% else %>

  <div class="container">
    <%= link_to 'Спроси меня', new_question_path(user_id: @user.id),
      class: 'button button-yellow' %>

    <p class="mt">
      <%= render 'questions/form', question: @question %>
    </p>
  </div>

  <div class="mt-sm container">
    <h2 class="title-lg">
      <%= @questions.count %>
      <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
    </h2>
  </div>

  <% @questions.each do |question| %>
    <div class="mt-sm container">
      <p class="mb text-sm text-grey">
        Вопрос <%= link_to "##{question.id}", question_path(question) %>
      </p>
      <%= render question %>
    </div>
  <% end %>

<% end %>